baseURL = "www.mattchannn.github.io"
languageCode = "en-us"
title = "Mat's Blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Mat - All rights reserved"
enableEmoji = true
publishDir = "public"
assetDir = "/static"

#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"
[params]
logo = "/images/blog-logo.png"
description = "the clean blog!"
backgroundImage = "/images/background-image.jpg"
customCSS = ["/css/list.css"]

[params.meta]
description = "Matt's Blog is a blog that is powered by HUGO, which provides blog posts and technical documentation"

#mailchimp = "you can provide a mailchimp-link here"
[params.author]
name = "Mat CHAN"
thumbnail = "/images/author.png"
description = "Author"

[params.index]
## picture = "/images/author.png"
## title = "Mat CHAN"
subtitle = "Welcome to Mat's Blog! A blog for technical guy, developers and mostly for myself."
##mdtext = '''
### Currently trying to get this blog running, still don't know what the blog will be about!\
### **This textblock is a demonstration of the mdtext-param.**\
### ### This is a markdown heading
### '''
mdtext = '''
This website is served as a place that contains [blog posts](/blog) and [cheatsheets](/doc).
'''
alertbar = false

[params.social]
github = "https://github.com/mattchannn"
linkedin = "https://www.linkedin.com/in/mat-c-048371154/"

## Main Menu
[[menu.main]]
name = "Blog"
weight = 100
identifier = "blog"
url = "/blog"

## [[menu.main]]
## name = "About Me"
## identifier = "about"
## weight = 200
## url = "/"
[[menu.main]]
name = "Doc"
identifier = "Doc"
weight = 200
url = "/doc"
